from first import *
from unattended_package_installer import *
from repo import *
from sudoers import *
from ssh_acl import *
from time_zone import *
from upgrade_pc import *
from change_root_passwd import *
from update_policy_client import *
from iptables import *
from arp import *
from clamav import *
from ocsinventory_agent import *
from grub import *
from adjust_crondaily import *
##from delete_files import *
from copy_files import *
from mount_file_servers import *
from mount_usb_local import *
from set_log import *
